Models/AddPizza.cs
using System;
namespace PizzaMania.Models
{
	public class AddPizza
	{
		public	Pizza Pizza { get; set; }

        public List<int> Ingredients { get; set; }
	}
}

Models/CartModel.cs
using System.ComponentModel.DataAnnotations;
using Microsoft.AspNetCore.Identity;

namespace PizzaMania.Models;

public class Cart
{
    [Key]
    public int Id { get; set; }

    public List<CartObjects> CartObjects { get; set; } = new List<CartObjects>();
}

Models/CartObjectModel.cs
using System.ComponentModel.DataAnnotations;
using Microsoft.AspNetCore.Identity;

namespace PizzaMania.Models;

public class CartObjects
{
    [Key]
    public int Id { get; set; }

    public int Quantity { get; set; } 

    public Pizza Pizza { get; set; } = new Pizza();
}

Models/IngredientModel.cs
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using Microsoft.AspNetCore.Identity;
namespace PizzaMania.Models;


    public class Ingredient
    {
        [Key]
        public int Id { get; set; }

        public string Name { get; set; }

        public List<Pizza> Pizzas { get; set; } = new List<Pizza>();
    }

Models/OrderModel.cs
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using Microsoft.AspNetCore.Identity;
namespace PizzaMania.Models;


    public class Order
    {
        [Key]
        public int Id { get; set; }

        public string Address { get; set; }

        public string? AdditionNotes { get; set; }

        public string? Status { get; set; } = " ";

    public List<CartObjects> CartObjects { get; set; } = new List<CartObjects>();

        
    }

Models/PizzaModel.cs
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using Microsoft.AspNetCore.Identity;

namespace PizzaMania.Models;

public class Pizza
{
    [Key]
    public int Id { get; set; }

    public string Name { get; set; }

    public string? Photo { get; set; }

    [NotMapped]
    public IFormFile? formFile { get; set; }

    public double Price { get; set; }


    public List<Ingredient>? Ingredients { get; set; } = new List<Ingredient>();
}

Models/UserModel.cs
using Microsoft.AspNetCore.Identity;

namespace PizzaMania.Models;

public class User: IdentityUser
{
    public Cart cart { get; set; } = new Cart();
}

Controllers/AppRolesController.cs
using System;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Identity;
using Microsoft.AspNetCore.Mvc;

namespace PizzaMania.Controllers
{
	[Authorize (Roles = "SuperAdmin")]
	public class AppRolesController : Controller
    {
		private readonly RoleManager<IdentityRole> _roleManager;

		public AppRolesController(RoleManager<IdentityRole> roleManager) {

			_roleManager = roleManager;
		}


		public IActionResult Index()
		{
			var roles = _roleManager.Roles;
			return View(roles);

		}

        public IActionResult Create()
        {
            return View();
        }


        
        public async Task<IActionResult> Delete(string id)
        {
			var x = _roleManager.Roles.FirstOrDefault(x => x.Id == id);
			await _roleManager.DeleteAsync(x);


            return RedirectToAction("Index");
        }



        [HttpPost]
		public async  Task<IActionResult> Create(IdentityRole model )
		{
			if (!_roleManager.RoleExistsAsync(model.Name).GetAwaiter().GetResult())
			{
				_roleManager.CreateAsync(new IdentityRole(model.Name)).GetAwaiter().GetResult();

			}

			return RedirectToAction("Index");
		}

      




    }
}

Controllers/HomeController.cs
using System.Diagnostics;
using Microsoft.AspNetCore.Mvc;
using PizzaMania.Models;

namespace PizzaMania.Controllers;

public class HomeController : Controller
{
    

    public HomeController()
    {
       
    }

    public IActionResult Index()
    {

          return View();
    }

 
}

Controllers/UserController.cs
using System;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Identity;
using Microsoft.AspNetCore.Mvc;
using PizzaMania.Models;

namespace PizzaMania.Controllers
{
    [Authorize(Roles = "SuperAdmin")]
    public class UserController : Controller
    {
        private readonly UserManager<User> _user;
        private readonly RoleManager<IdentityRole> _role;

        public UserController(UserManager<User> user, RoleManager<IdentityRole> role) {

            _user = user;
            _role = role;
        }


        public IActionResult Index()
        {
            var user = _user.Users;
            return View(user);

        }
 

        public IActionResult EditUser(string id)
        {
            var user = _user.Users.FirstOrDefault(x => x.Id == id);
       
            return View(user);
        }

       
        [HttpPost]
        public async Task<IActionResult> EditUser(string id, string permission)
        {
            var user = _user.Users.FirstOrDefault(x => x.Id == id);
            await _user.AddToRoleAsync(user, permission);
            return RedirectToAction("EditUser", new { user.Id });
        }


        public async Task<IActionResult> DeleteUser(string id)
        {

            var user = _user.Users.FirstOrDefault(x => x.Id == id);
            await _user.DeleteAsync(user);

            return RedirectToAction("Index");
        }


        public async Task<IActionResult> RemoveRole(string role, string id)
        {

            var user = _user.Users.FirstOrDefault(x => x.Id == id);
            await _user.RemoveFromRoleAsync(user, role);

            return RedirectToAction("EditUser" ,new { id });
        }
    }



    
}

Views/AppRoles/Create.cshtml
@using Microsoft.AspNetCore.Identity
@model IdentityRole
@{

    ViewData["Title"] = "Create Roles";

}

<div class="row">
    <div class="col-md-4">
        <form method="post">
            <h2> Create Role</h2>
            <hr />
             <div asp-validation-summary="ModelOnly" class="text-danger"></div>
             <div class="form-floating">
                 <input asp-for="Name" class="form-control" aria-required="true" />
                 <label asp-for="Name"></label>
                 <span asp-validation-for="Name" class="text-danger"></span>
             </div>
             <button type="submit" class="btn btn-primary">SAVE</button>
          </form>
        </div>
</div>

Views/AppRoles/Index.cshtml
@using Microsoft.AspNetCore.Identity
@model IEnumerable<IdentityRole>


@{

    ViewData["Title"] = "Roles";

}


<h1>Roles</h1>

<p>
    <a asp-action="Create">Create new Role</a>
</p>

<table class="table">

    <thead>
        <tr>
            <th>@Html.DisplayNameFor(model => model.Id)</th>
            <th>@Html.DisplayNameFor(model => model.Name)</th>
            <th></th>
        </tr>
    </thead>
    <tbody>
        @foreach(var i in Model) {
                <tr>
                    <td>@Html.DisplayFor(modelI => i.Id)</td>
                    <td>@Html.DisplayFor(modelI => i.Name)</td>
                    <td><a asp-action="Delete" asp-route-id="@i.Id">Delete</a></td>
                    <td></td>
                </tr>
    
            }
    </tbody>
</table>

Views/Cart/Index.cshtml
@using PizzaMania.Models
@model Cart
@{

    ViewData["Title"] = "Cart";
    double totcart = 0;
    string notes = "";
    string address = "";
    bool disablecart = !Model.CartObjects.Any();
}


<div class="container-fluid">
    @foreach (var i in Model.CartObjects)
    {
        var quantity = i.Quantity;
        double subtot = quantity * i.Pizza.Price;
        totcart += subtot;

        <h1>@i.Pizza.Name</h1>
        <h2>@i.Pizza.Price€</h2>
        <img src="@i.Pizza.Photo" width="150px" height="150px" />
        <form class="" asp-action="UpdateQuantity" asp-route-id="@i.Id">
            <input class="form-control" onchange="this.form.submit()" asp-for="@quantity" />
        </form>
        <h2>Subtot: @subtot</h2>
        <hr />
    }
    <h1>Tot Cart: @totcart</h1>

    <form asp-action="Checkout">
        <input class="form-control" asp-for="@address" />
        <textarea asp-for="@notes"></textarea>
        <button  disabled="@disablecart" type="submit" class="btn btn-primary">Order</button>
    </form>
</div>

Views/Home/Index.cshtml
@{
    ViewData["Title"] = "Home Page";
}

<div class="text-center">
    <h1 class="display-4">Welcome</h1>
    <p>Learn about <a href="https://docs.microsoft.com/aspnet/core">building Web apps with ASP.NET Core</a>.</p>
</div>

Views/Ingredient/AddIngredient.cshtml
@using PizzaMania.Models;
@model Ingredient
@{

    ViewData["Title"] = "Add Ingredient";
}

<h1 class="text-center">@ViewData["Title"]</h1>
<form class="row g-3" method="post" >
    <div class="col-md-12">
        <label class="form-label">Name</label>
        <input asp-for="@Model.Name" type="text" class="form-control" id="Name">
    </div>
    <div class="col-12 d-flex justify-content-center">
        <button type="submit" class="btn btn-primary btn-lg px-5 mt-3">Create</button>
    </div>
</form>

Views/Ingredient/Index.cshtml
@using PizzaMania.Models
@model List<Ingredient>
@{

    ViewData["Title"] = "Ingredient";
}




<div class="container-fluid">
    <h1 class="text-center">@ViewData["Title"]</h1>
    <button onclick="location.href='@Url.Action("AddIngredient")'" class="btn btn-success">Add Ingredient</button>
    <table class="table">
        <thead>
            <tr>
                <th scope="col">Id</th>
                <th scope="col">Name</th>
                <th></th>
            </tr>
        </thead>
        <tbody>
            @foreach (var ingredient in Model)
            {
                <tr>
                    <td>@ingredient.Name</td>
               
                    <td><a asp-action="EditIngredient" asp-route-id="@ingredient.Id">Edit</a> <a asp-action="DeleteIngredient" asp-route-id="@ingredient.Id">Delete</a></td>
                </tr>
            }
        </tbody>
</div>
</table>

Views/Order/Index.cshtml
@using PizzaMania.Models
@model List<Order>
@{

    ViewData["Title"] = "Order";
    double total = 0;
}




<div class="container-fluid">
    <h1 class="text-center">@ViewData["Title"]</h1>
    <table class="table">
        <thead>
            <tr>
                <th scope="col">Id</th>
                <th scope="col">Pizze</th>
                <th scope="col">Address</th>
                <th scope="col">Notes</th>
                <th scope="col">Status</th>
                <th scope="col">Total</th>
                <th></th>
            </tr>
        </thead>
        <tbody>
            @foreach (var order in Model)
            {
                    var status = order.Status;
                <tr>
                    <th scope="row">@order.Id</th>
                    <td>
                        @foreach (var i in order.CartObjects)
                            {
                                var sub = i.Quantity * i.Pizza.Price;
                                total += sub;
                            <span>@i.Pizza.Name (@i.Quantity)</span>
                        }
                    </td>
                    <td>@order.Address</td>
                    <td>@order.AdditionNotes</td>
                    <td>
                        <form asp-action="UpdateStatus" asp-route-id="@order.Id">
                            <select asp-for="@status" onchange="this.form.submit()">
                                <option disabled value=" ">Change Status</option>
                                <option value="Accepted">Accepted</option>
                                <option value="In Progress">In Progress</option>
                                <option value="Delivered">Delivered</option>
                            </select>
                        </form>
                    </td>
                    <td>@total</td>
                    <td> <a asp-action="DeleteOrder" asp-route-id="@order.Id">Delete</a></td>
                </tr>
            }
        </tbody>
</div>
</table>

Views/Pizza/AddPizza.cshtml
@using PizzaMania.Models;
@using PizzaMania.Data;
@model AddPizza
@inject ApplicationDbContext _db;
@{

    var ingredient = _db.Ingredients.ToList();
    ViewData["Title"] = "Add Customer";
}

<h1 class="text-center">@ViewData["Title"]</h1>
<form class="row g-3" method="post" enctype="multipart/form-data">
    <div class="col-md-6">
        <label class="form-label">Name</label>
        <input asp-for="@Model.Pizza.Name" type="text" class="form-control" id="Name">
    </div>
    <div class="col-md-6">
        <label class="form-label">Price</label>
        <input asp-for="@Model.Pizza.Price" type="text" class="form-control" id="Price">
    </div>
    <div class="col-6">
        <label class="form-label">Ingredients</label>
        <select  class="form-control" multiple asp-for="@Model.Ingredients">
            @foreach(var i in ingredient)
            {
               <option value="@i.Id">@i.Name</option>
            }
        </select>
    </div>
    <div class="col-md-6">
        <label class="form-label">Upload Photo</label>
        <input asp-for="@Model.Pizza.formFile" type="file" class="form-control" id="Photo">
    </div>
    <div class="col-12 d-flex justify-content-center">
        <button type="submit" class="btn btn-primary btn-lg px-5 mt-3">Create</button>
    </div>
</form>

Views/Pizza/Index.cshtml
@using PizzaMania.Models
@model List<Pizza>
@{

    ViewData["Title"] = "Pizze";
}




<div class="container-fluid">
    <h1 class="text-center">@ViewData["Title"]</h1>
    <button onclick="location.href='@Url.Action("AddPizza")'" class="btn btn-success">Add Pizza</button>
    <table class="table">
        <thead>
            <tr>
                <th scope="col">Id</th>
                <th scope="col">Name</th>
                <th scope="col">Price</th>
                <th scope="col">Ingredients</th>
                <th></th>
            </tr>
        </thead>
        <tbody>
            @foreach (var pizza in Model)
            {
                <tr>
                    <th scope="row">@pizza.Id</th>
                    <td>@pizza.Name</td>
                    <td>@pizza.Price</td>
                    <td>
                        @foreach (var i in pizza.Ingredients)
                        {
                            <span>@i.Name</span>
                        }
                    </td>
                    <td><a asp-action="EditPizza" asp-route-id="@pizza.Id">Edit</a> <a asp-action="DeletePizza" asp-route-id="@pizza.Id">Delete</a></td>
                </tr>
            }
        </tbody>
</div>
</table>

Views/Pizza/PizzaDetails.cshtml
@using PizzaMania.Models
@model Pizza
@{

    ViewData["Title"] = $"Pizza {Model.Name}";
    var quantity = 0;
}


<form asp-action="AddToCart" asp-route-id="@Model.Id">

    <div class="container-fluid">
        <h1 class="text-center">@ViewData["Title"]</h1>
        <h2>@Model.Price€</h2>
        <h3>Ingredients:</h3>
        <ul>
            @foreach (var i in Model.Ingredients)
            {
                <li>@i.Name</li>
            }
        </ul>
        <img src="@Model.Photo" width="300px" height="300px" />
        <input class="form-control" asp-for="@quantity" type="number" />
        <button onclick="this.form.submit() " class="btn btn-primary">Add To Cart</button>

    </div>
</form>

Views/Pizza/Store.cshtml
@using PizzaMania.Models
@model List<Pizza>
@{

    ViewData["Title"] = "Pizze Store";
}




<div class="container-fluid">
    <h1 class="text-center">@ViewData["Title"]</h1>
    <div class="row d-flex justify-content-center"">
        @foreach (var pizza in Model)
        {
            <div class="card col-md-3 mx-3 my-3" style="width: 18rem;">
                <img class="card-img-top" src="@pizza.Photo" alt="@pizza.Name">
                <div class="card-body">
                    <h5 class="card-title">@pizza.Name</h5>
                    <a href="/pizza/pizzadetails/@pizza.Id" class="btn btn-primary">Details</a>
                </div>
            </div>
        }
    </div>
  
</div>

Views/Shared/_Layout.cshtml
@using Microsoft.AspNetCore.Identity
@inject SignInManager<User> SignInManager
@inject UserManager<User> UserManager
@inject RoleManager<IdentityRole> role

@{
    ViewData["Title"] = "Pizzamania";
}

<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>@ViewData["Title"]</title>
    <link rel="stylesheet" href="~/lib/bootstrap/dist/css/bootstrap.min.css" />
    <link rel="stylesheet" href="~/css/site.css" asp-append-version="true" />
    <link rel="stylesheet" href="~/AgenziaSpedizioni.styles.css" asp-append-version="true" />
</head>
<body>
    <header>
        <nav class="navbar navbar-expand-sm navbar-toggleable-sm navbar-light bg-white border-bottom box-shadow mb-3">
            <div class="container-fluid">
                <a class="navbar-brand" asp-area="" asp-controller="Home" asp-action="Index">@ViewData["Title"]</a>
                <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target=".navbar-collapse" aria-controls="navbarSupportedContent"
                        aria-expanded="false" aria-label="Toggle navigation">
                    <span class="navbar-toggler-icon"></span>
                </button>
                <div class="navbar-collapse collapse d-sm-inline-flex justify-content-between">
                    <ul class="navbar-nav flex-grow-1">
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Pizza" asp-action="Store">Store</a>
                        </li>
                        @if (SignInManager.IsSignedIn(User) && await UserManager.IsInRoleAsync(UserManager.Users.FirstOrDefault(x => x.Id == UserManager.GetUserId(User)), "Manager"))
                        {
                            <li class="nav-item">
                                <a class="nav-link text-dark" asp-area="" asp-controller="Order" asp-action="Index">Order</a>
                            </li>
                            <li class="nav-item">
                                <a class="nav-link text-dark" asp-area="" asp-controller="Pizza" asp-action="Index">Pizze</a>
                            </li>
                            <li class="nav-item">
                                <a class="nav-link text-dark" asp-area="" asp-controller="Ingredient" asp-action="Index">Ingredients</a>
                            </li>

                        }
                    </ul>
                    @if (SignInManager.IsSignedIn(User) && await UserManager.IsInRoleAsync(UserManager.Users.FirstOrDefault(x => x.Id == UserManager.GetUserId(User)), "SuperAdmin"))
                    {
                       <ul class="navbar-nav">
                           @if (SignInManager.IsSignedIn(User))
                               {
                                   <li class="nav-item">
                                   <a class="nav-link text-dark" asp-area="" asp-controller="Cart" asp-action="Index">Cart</a>
                                    </li>
                               }
                               <li class="nav-item">
                                   <a class="nav-link text-dark" asp-area="" asp-controller="AppRoles" asp-action="Index">Permission</a>
                               </li>
                               <li class="nav-item">
                                   <a class="nav-link text-dark" asp-area="" asp-controller="User" asp-action="Index">Users</a>
                               </li>
                           </ul>
                    }
                    <partial name="_LoginPartial" />
                </div>
            </div>
        </nav>
    </header>
    <div class="container">
        <main role="main" class="pb-3">
            @RenderBody()
        </main>
    </div>

    <script src="~/lib/jquery/dist/jquery.min.js"></script>
    <script src="~/lib/bootstrap/dist/js/bootstrap.bundle.min.js"></script>
    <script src="~/js/site.js" asp-append-version="true"></script>
    @await RenderSectionAsync("Scripts", required: false)
</body>
</html>

Views/User/EditUser.cshtml
@using PizzaMania.Models
@using Microsoft.AspNetCore.Identity
@model User
@inject RoleManager<IdentityRole> role
@inject UserManager<User> user

@{
    string permission = "";
}

<div>
    <h1> Roles of @Model.UserName</h1>
    <form method="post">
        <select asp-for="@permission">
            @foreach (var i in role.Roles)
            {
                <option value="@i.Name">@i.Name</option>
            }
        </select>
        <button type="submit" class="btn btn-primary">Save</button>
    </form>

    @foreach (var role in await user.GetRolesAsync(Model))
    {
        <ul>
            <li>@role  <a asp-action="RemoveRole" asp-route-role="@role" asp-route-id="@Model.Id">Delete</a></li>

        </ul>

    }
</div>
    

Views/User/Index.cshtml
@using Microsoft.AspNetCore.Identity
@using PizzaMania.Models
@model IEnumerable<User>


@{

    ViewData["Title"] = "User";
}


<h1>@ViewData["Title"]</h1>



<table class="table">

    <thead>
        <tr>
            <th>@Html.DisplayNameFor(model => model.UserName)</th>
            <th></th>
            <th></th>
        </tr>
    </thead>
    <tbody>
        @foreach (var i in Model)
        {
            <tr>
                <td>@Html.DisplayFor(modelI => i.UserName)</td>

                <td><a asp-action="EditUser" asp-route-id="@i.Id">Manage Role</a></td>
                <td><a asp-action="DeleteUser" asp-route-id="@i.Id">Delete</a></td>

            </tr>

        }
    </tbody>
</table>